insta/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include # new
from django.contrib.auth import views as auth_views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls')), # new
    path('accounts/', include('django.contrib.auth.urls')), # new
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from .views import HomePageView,CreatePostView,addlike,PostPlus,PostViewSet,login_rest
from django.urls import path
from rest_framework.routers import DefaultRouter

router = DefaultRouter()

urlpatterns = [
    path('home', HomePageView.as_view(), name='home'),
    path('new_post', CreatePostView.as_view(), name='new_post'),
    path('add_like/<int:pk>', addlike , name='add_like'),
    path('postplus/', PostPlus.as_view() , name='post_plus'),
    path('rest_login/', login_rest , name='login_rest'),
]

#DRF
router.register(r'rest_post', PostViewSet, basename='user')
urlpatterns += router.urls

post/models.py
from django.db import models



class Post(models.Model):
    text = models.CharField(max_length=200)
    title = models.TextField(null=True)
    cover = models.ImageField(upload_to='images/', default= '/images/Tiffiza.png', null=True, blank=True)
    likes = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True,null=True)

    def __str__(self):
        return str(self.title)


class PostDetail(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,related_name='pd')
    comment = models.CharField(max_length=200,null=True)
    
    def __str__(self):
        return str(self.post.title)
    

post/views.py
from django.shortcuts import render

from django.views.generic import ListView,CreateView
from django.urls import reverse_lazy # new
from .form import PostForm
from .models import Post
from django.shortcuts import redirect
from .models import Post
from django.views import View
from django.shortcuts import get_object_or_404
##DRF
from rest_framework import viewsets
from rest_framework.response import Response
from .PostSerializer import PostSerializer,PostCreateSerializer
from django.contrib.auth import authenticate

##auth
from rest_framework.authtoken.models import Token
from rest_framework.permissions import IsAuthenticated
from rest_framework.decorators import api_view,permission_classes,authentication_classes
from rest_framework.authentication import SessionAuthentication, BasicAuthentication

class HomePageView(ListView):
    model = Post
    template_name = 'post/index.html'

class CreatePostView(CreateView): # new
    model = Post
    form_class = PostForm
    template_name = 'post/new_post.html'
    success_url = reverse_lazy('home')


def addlike(request,pk):
    if request.method == 'GET':
        print(pk)
        obj  = Post.objects.get(pk=pk)
        obj.likes+=1
        obj.save()
        
    else:
        pass
        # Code block for GET request (will also match PUT, HEAD, DELETE, etc)    
    return redirect('/home')    

class PostPlus(View):
    
    template_name = 'post/postplus.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'message': 'new post'})

    def post(self, request, *args, **kwargs):
        post = PostForm(request.POST, request.FILES)  
        if post.is_valid():  
            obj = post.save(commit=False)
            obj.likes = 55
            obj.save()
        
        return render(request, self.template_name, {'message': 'new post added'})    

####DRF

class PostViewSet(viewsets.ViewSet):
    

    
    def get_permissions(self):
    
        if self.action == 'list' or self.action == 'password_reset':
            permission_classes = [IsAuthenticated]
        else:
            permission_classes = []
        return [permission() for permission in permission_classes]
    
    def list(self, request):
        queryset = Post.objects.all()
        serializer = PostSerializer(queryset, many=True)
        return Response(serializer.data)

    def retrieve(self, request, pk=None):
        queryset = Post.objects.all()
        post = get_object_or_404(queryset, pk=pk)
        serializer = PostSerializer(post)
        return Response(serializer.data)  

    def create(self, request):
        serializer = PostCreateSerializer(data=request.data)
        if serializer.is_valid(raise_exception=True):
            
            serializer.save()
        return Response(serializer.data)  

    def partial_update(self, request, pk=None):
        instance  = Post.objects.get(pk = pk)
        serializer = PostCreateSerializer(instance, data=request.data, partial=True)
        if serializer.is_valid(raise_exception=True):
            #.... Your code ....
            serializer.save()
        return Response(serializer.data)  

    def update(self, request, pk=None):
        instance  = Post.objects.get(pk = pk)
        serializer = PostCreateSerializer(instance, data=request.data)
        if serializer.is_valid(raise_exception=True):
            #.... Your code ....
            serializer.save()
        return Response(serializer.data)   

    def destroy(self, request, pk=None):
        instance  = Post.objects.get(pk = pk)
        instance.delete()
        return Response("deleed")  


@api_view(["POST"])
#@permission_classes([IsAuthenticated])
#@authentication_classes([SessionAuthentication, BasicAuthentication])
def login_rest(request):
    username = request.data.get("username")
    password = request.data.get("password")
    
    if username is None or password is None:
        return Response({'error': 'Please provide both username and password'},
                        status=HTTP_400_BAD_REQUEST)
    user = authenticate(username=username, password=password)
    if not user:
        return Response({'error': 'Invalid Credentials'},
                        status=HTTP_404_NOT_FOUND)
    token, _ = Token.objects.get_or_create(user=user)
    
    
    data = {
            'token': token.key,
            'username': user.username,
                        
                    }
    
    return Response(data)          

post/templates/post/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>MLSU CHATBOOK</title>

  <!-- Bootstrap core CSS -->
  <script src="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"></script>
  <link href="{% static 'post/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
 

  <!-- Custom styles for this template -->
  <link href="{% static 'post/css/blog-home.css'%} " rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">MLSU CHATBOOK</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'home' %}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'post_plus' %}">Post Plus</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'new_post' %}">New Post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <!-- Blog Entries Column -->
      <div class="col-md-8">
        {% if user.is_authenticated %}
        <h1 class="my-4">Hii,
          <small>{{ user.username }}!</small>
        </h1>
        {% else %}
            <p>You are not logged in</p>
            <a href="{% url 'login' %}">login</a>
        {% endif %}
            
            
        {% block content %}
        {% endblock %}

        

       

        <!-- Pagination -->
        <ul class="pagination justify-content-center mb-4">
          <li class="page-item">
            <a class="page-link" href="#">&larr; Older</a>
          </li>
          <li class="page-item disabled">
            <a class="page-link" href="#">Newer &rarr;</a>
          </li>
        </ul>

      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Search Widget -->
        <div class="card my-4">
          <h5 class="card-header">Search</h5>
          <div class="card-body">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-btn">
                <button class="btn btn-secondary" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div>

        <!-- Categories Widget -->
        <div class="card my-4">
          <h5 class="card-header">Categories</h5>
          <div class="card-body">
            <div class="row">
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">Web Design</a>
                  </li>
                  <li>
                    <a href="#">HTML</a>
                  </li>
                  <li>
                    <a href="#">Freebies</a>
                  </li>
                </ul>
              </div>
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">JavaScript</a>
                  </li>
                  <li>
                    <a href="#">CSS</a>
                  </li>
                  <li>
                    <a href="#">Tutorials</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>

        <!-- Side Widget -->
        <div class="card my-4">
          <h5 class="card-header">Side Widget</h5>
          <div class="card-body">
            You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
          </div>
        </div>

      </div>

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'post/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'post/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>

post/templates/post/index.html
{% extends 'post/base.html' %}

{% block content%}

{% for post in object_list reversed %}
          
          <!-- Blog Post -->
        <div class="card mb-4">
            <img class="card-img-top" src="{{ post.cover.url}}" alt="Card image cap">
            <div class="card-body">
              <h2 class="card-title">{{ post.title }}</h2>
              <p class="card-text">{{ post.text }}</p>
              <a href="#" class="btn btn-primary">Read More &rarr;</a>
            </div>
            <hr>
            <p class="card-text">     &nbsp comments</p>
            <hr>
            {% for i in post.pd.all %}
            <div class="card-body">
                <div class="card-footer text-muted">
              
                {{i.comment}}
              
                </div>
              </div>
            {% endfor %}
            <div class="card-footer text-muted">
                <a class="nav-link" href="{% url 'add_like' post.id %}"><i class="fa fa-thumbs-up" aria-hidden="true"></i>like({{post.likes}})</a> posted on {{post.created_at}}
              
        
            </div>
          </div>

        {% endfor %}
 {% endblock %}        
        

post/templates/post/new_post.html
{% extends 'post/base.html' %}

{% block content%}
<h3>Create Post Page</h3>
<br>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-success" >Submit New Post</button>
</form>
{% endblock %}

post/templates/post/postplus.html
{% extends 'post/base.html' %}

{% block content%}
<form method ="post" action="{% url 'post_plus' %}" enctype="multipart/form-data">
        {% csrf_token %}
    <div class="form-group">
      <label for="email">Label</label>
      <input type="text" name="title" class="form-control" id="email">
    </div>
    <div class="form-group">
      <label for="pwd">Text</label>
      <input type="text" name="text" class="form-control" id="pwd">
    </div>
    <div class="form-group">
        <label for="pwd">Image</label>
        <input type="file" accept="image/*" name="cover" id="id_cover" class="form-control" id="pwd">
      </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
  {% endblock %} 